[package]
name = "wlist_native_test"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "^1.0"
tracing = "~0.1"
tokio = { version = "^1.40", features = ["macros", "rt-multi-thread"] }

tracing-subscriber = "~0.3"
wlist_native = { path = "../wlist_native" }
